### ISSUE TITLE
日志总是会写入today.log

### ISSUE THREAD

**Issue by BigCookie233** [MuRainBot/MuRainBot2#5]
日志总是会写入today.log

预期：

以往的日志会被命名为xxxx-xx-xx.log

实际:

新的日志会被追加至today.log末尾

系统环境：Arch Linux (内核: 6.7.9-arch1-1)
Python版本: 3.11.8

**Comment by xiaosuawa** [comment]
这似乎是logging库的问题，我在本地测试时也出现过，请尝试删除today.log后再测试。

**Comment by BigCookie233** [comment]
删除today.log后再运行依然会出现此问题

**Comment by xiaosuawa** [comment]
> 删除today.log后再运行依然会出现此问题

可否提供一个截图

**Comment by BigCookie233** [comment]
![d30a1d4a-b962-4049-a144-31c4c2e5ec8c](https://github.com/xiaosuyyds/MuRainBot2/assets/86756026/05ab1170-deb9-4b7d-8b01-4618d1f0fe9c)

**Comment by xiaosuawa** [comment]
到第二天再运行看一下，如果还不行我在考虑修复

**Comment by xiaosuawa** [comment]
应该是解决了吧，我关闭了哈

**Comment by BigCookie233** [comment]
莫名其妙地好了，很奇怪

**Comment by xiaosuawa** [comment]
对我也遇到过，删掉就好了
