### ISSUE TITLE
跪求新增插件：监控目标群信息

### ISSUE THREAD

**Issue by Davidyang1989** [MuRainBot/MuRainBot2#52]
请问会增加一个实时监控获取目标群消息的插件吗?

**Comment by xiaosuawa** [comment]
MuRainBot2本身是一个Onebot框架兼SDK，本项目插件文件夹提供的插件仅做为示例，你描述的功能其实光靠log也能看，不过如果要实现单独获取某个群消息的话你可以自己写一个插件来实现，在注册一个群消息事件的监听器，处理事件的部分添加一个if判断只通过指定群号的消息，然后在后面添加上你想进行的操作，可以参看本项目的文档以及示例插件

**Comment by Davidyang1989** [comment]
即使不是自己是群主\管理员的qq群也可以吗？
还是不论怎样都受制于qq官方机器人的限制？

**Comment by HarcicYang** [comment]
> 即使不是自己是群主\管理员的qq群也可以吗？
> 
> 还是不论怎样都受制于qq官方机器人的限制？


请理解：
- 什么是QQ协议、协议库；
- 基于协议库实现的QQ Bot有哪些features；
- 什么是[OneBot](https://11.onebot.dev)协议；
